Hiratake/hiratake-web

src/components/AppSwitch.vue
src/components/TheHeader.vue

Switchがオフの場合の背景色が白にならない

---

package.json
src/components/AppSwitch.vue
src/components/TheHeader.vue
src/main.js
yarn.lock

FontAwesomeを使えるようにする

---

nuxt.config.js
package.json
yarn.lock

タグマネージャを導入

---

nuxt.config.js
package.json
yarn.lock

sitemap.xmlを出力する

---

nuxt.config.js
pages/_slug.vue

記事のgithubへのリンクが正しくない問題を修正

---

pages/_slug.vue

編集提案のアイコンの色が正しくないのを修正

---

package-lock.json
package.json
pages/api/preview.ts
pages/blog/[id].tsx

ブログ記事のプレビュー表示機能を追加

---

package-lock.json
package.json
pages/api/preview.ts

プレビュー機能のサンプルに `node-fetch` が使用されていたためインストールしたが、使っていないので削除。

不要なパッケージを削除

---

pages/_app.tsx
pages/api/clear.ts
pages/blog/[id].tsx

プレビューモードを解除できるようにする

---

pages/api/preview.ts
pages/blog/[id].tsx
pages/blog/index.tsx
pages/contact.tsx
pages/privacy.tsx
types/cms.ts

ブログ記事の型指定の誤りを修正

---

components/PageContainer.tsx
pages/blog/[id].tsx
pages/blog/index.tsx

ブログ記事のタグ表示を追加

---

content/index.md
pnpm-lock.yaml
web/nuxt.config.ts
web/package.json
web/src/app.config.ts
web/src/components/TheFooter.vue
web/src/components/content/ProseImg.vue
web/src/components/content/TopProfile.vue
web/src/layouts/default.vue

- トップページのプロフィール表示用コンポーネントを追加
- アイコン画像表示のためNuxtのImageモジュールを追加

feat: トップページのプロフィール表示を追加

---

web/src/components/content/ContentListItem.vue
web/src/components/content/ProseImg.vue
web/src/layouts/default.vue

ブログ記事の表示を改善

---

web/nuxt.config.ts

コードブロックにシンタックスハイライトを適用

---

web/src/layouts/default.vue

コンテンツが画面外にオーバーフローする問題を修正

---

web/src/components/TheHeader.vue

chore: モバイル表示時のヘッダーの余白を調整

---

.lintstagedrc.json
.textlintrc.js
README.md
package.json
packages/README.md
packages/textlint-rule-preset-custom/.eslintrc.js
packages/textlint-rule-preset-custom/README.md
packages/textlint-rule-preset-custom/index.js
packages/textlint-rule-preset-custom/package.json
pnpm-lock.yaml

ci: textlintを導入

---

.changeset/weak-taxis-check.md
.github/workflows/release.yaml
.gitignore
README.md
package.json
packages/README.md
packages/textlint-rule-space-around-bold/README.md
packages/textlint-rule-space-around-bold/package.json
packages/textlint-rule-space-around-bold/src/index.ts
packages/textlint-rule-space-around-bold/test/index-test.ts
packages/textlint-rule-space-around-bold/tsconfig.json
pnpm-lock.yaml

feat: 太字の前後に半角スペースを入れるtextlintルールの追加

---

web/src/components/DocumentDrivenNotFound.vue
web/src/components/TheSeo.vue
web/src/layouts/default.vue
web/tailwind.config.js

feat: コンテンツが存在しない場合の表示を追加

---

web/src/components/content/ContentList.vue
web/src/components/content/ContentListItem.vue
web/src/layouts/default.vue
web/src/types/index.ts

chore: 記事一覧を調整

---

web/src/layouts/default.vue

feat: 前後の記事へのリンクを追加

---

web/src/layouts/default.vue

fix: 最初の投稿と最新の投稿で前後の記事へのリンクが表示されない問題を修正

---

package.json
packages/eslint-config-custom/package.json
packages/social-share/package.json
pnpm-lock.yaml
web/package.json

`@nuxt/devtools` は以下の対応待ち
- https://togithub.com/nuxt/devtools/issues/368

build(deps): 依存関係を更新

---

.changeset/red-mails-teach.md
packages/social-share/src/components/SocialShare/types.ts
packages/social-share/src/components/SocialShare/utils/index.ts

feat: シェアコンポーネントのSNS一覧にXを追加

---

web/src/layouts/default.vue

fix: ダークモード時にシェアボタンのサーバ入力の表示が適切でない問題を修正

---

pnpm-lock.yaml
web/package.json

`@types/node` の更新時に `web` と `packages/tsconfig` の 2 箇所更新するのがめんどいので調整。

build: webの依存関係にtsconfigパッケージを追加

---

content/blog/index.md
web/src/components/content/ArticleList.vue
web/src/components/content/ArticleListItem.vue

fix: contentListコンポーネントの重複を修正

---

.github/renovate.json

- `minor` と `patch` をまとめて更新するよう変更

ci: renovateの設定を変更

---

web/src/server/routes/feed.xml.ts
web/src/server/utils/content.ts

RSSフィードにブログ記事本文の内容を追加。
- close #447

feat: rssフィードにブログ記事本文の内容を追加

---

pnpm-lock.yaml
web/package.json

chore(deps): update dependency @nuxt/content

---

.changeset/wise-wombats-guess.md
packages/textlint-rule-front-matter/README.md
packages/textlint-rule-front-matter/src/index.ts
packages/textlint-rule-front-matter/test/index-test.ts

feat: 指定した正規表現に一致するかを検証するオプションを追加

---

web/src/components/content/ArticleRuby.vue

feat: ルビをふるためのコンポーネントを追加

---

content/about.md
content/contact.md
web/src/components/TheFooter.vue

- close #692 
- ウェブサイトのフッターに運営者情報ページへのリンクを追加

docs: 運営者情報ページを追加

---

web/nuxt.config.ts

Reverts Hiratake/hiratake-web#836

chore: ドメインを cloudflare の環境変数から取得するよう変更

---

.github/workflows/autofix.yaml
.github/workflows/ci.yaml
.github/workflows/release.yaml
package.json
pnpm-lock.yaml

build: node20系に更新

---

.vscode/extensions.json

- https://marketplace.visualstudio.com/items?itemName=Nuxtr.nuxtr-vscode

chore: vscodeのnuxtr拡張機能を推奨として追加

---

src/components/home/Blog.vue
src/components/home/Profile.vue

fix: トップページの左右の余白を修正

---

.github/workflows/autofix.yaml
.github/workflows/ci.yaml
package.json
pnpm-lock.yaml

build: nodeを22系へ更新

---

nuxt.config.ts
src/pages/[...slug].vue

fix: 存在しないブログページで404にならない問題を修正

---

.github/workflows/autofix.yaml
.github/workflows/ci.yaml

- https://togithub.com/actions/setup-node/issues/1351

ci: setup-nodeアクションをv5へ更新
